name: dvswitch
version: '0.9.5'
summary: live PAL/NTSC DV VideoMixer (network orientated) using FireWire 1394
description: dvswitch is a simple GUI DV VideoMixer assisted/initiated by CLI tools dvsource/dvsink
type: app

grade: devel
confinement: classic

parts:
  dvswitch-part:
    after: [desktop-gtk2]
    plugin: cmake
    build-packages: [libboost-thread-dev,libgtkmm-2.4-dev,libavcodec-dev,libasound2-dev,libxv-dev,libjack-jackd2-dev,liblo-dev,gettext,]
    stage-packages: [libpng12-0,dvgrab,libgdk-pixbuf2.0-0,hicolor-icon-theme]
#   organize:
#     usr/local/share/: usr/share/

apps:
  dvgrab:
    command: usr/bin/dvgrab
  dvswitch:
    command: bin/desktop-launch $SNAP/usr/bin/dvswitch
    plugs: [x11,wayland,network,network-bind,home,desktop,desktop-legacy]
  dvsink-files:
    command: usr/bin/dvsink-files
  dvsource-file:
    command: usr/bin/dvsource-file
  dvsource-dvgrab:
    command: usr/bin/dvsource-dvgrab
  dvsource-firewire:
    command: usr/bin/dvsource-firewire
