name: dvswitch
version: '0.9.5'
summary: live PAL/NTSC DV VideoMixer (network orientated) using FireWire 1394
description: dvswitch is a simple GUI DV VideoMixer assisted/initiated by CLI tools dvsource/dvsink

grade: devel
confinement: devmode

parts:
  dvswitch-part:
    plugin: cmake
    build-packages: [libboost-thread-dev,libgtkmm-2.4-dev,libavcodec-dev,libasound2-dev,libxv-dev,libjack-jackd2-dev,liblo-dev,gettext]
